#!/bin/zsh
cd Cpp
rename 's|^(\d+)[. ]+(.*)|P$1 $2|; s| |-|g' *cpp
rename -c -f *
cd ..
cd Java
rename 's|^(\d+)[. ]+(.*)|P$1 $2|; s| |-|g' *java
rename -c -f *
cd ..
cd Python3
rename 's|^(\d+)[. ]+(.*)|P$1 $2|; s| |-|g' *py
rename -c -f *
cd ..
